set ENABLE_TESTING=1
if not defined RS_MULTI_DEPS_DIRS set "RS_MULTI_DEPS_DIRS=!DEPENDENCIES_INSTALL_DIR!"
if not defined RS_OPENSSL_DIR set "RS_OPENSSL_DIR=!DEPENDENCIES_INSTALL_DIR!\openssl\!RS_BUILD_TYPE!"