//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by rsodbcsetup.rc
//
#define IDS_BADDSN                      1
#define VS_VERSION_INFO                 1
#define IDS_MSGTITLE                    2
#define IDS_ADVANCE_OPTION_DEF          3
#define IDOK2                           3
#define IDS_ADVANCE_SAVE                4
#define IDCANCEL2                       4
#define IDS_ROLLBACKERR_NOP             5
#define IDS_ROLLBACKERR_XACT            6
#define IDS_STRING7                     7
#define IDS_ROLLBACKERR_STMT            7
#define IDS_ADVANCE_CONNECTION          9
#define IDR_HTML_SCENABLECHECKBOX       103
#define DLG_CONNECTION                  107
#define DLG_ADVANCED                    108
#define DLG_FAILOVER                    109
#define DLG_POOLING                     111
#define DLG_SECURITY                    112
#define IDC_DSNAME                      400
#define IDC_DSNAMETEXT                  401
#define IDC_DESC                        404
#define IDC_SERVER                      407
#define IDC_DATABASE                    408
#define IDC_SSLMODE                     409
#define IDC_CID                         409
#define IDC_REGION                      410
#define IDC_DBUSER                      411
#define IDC_DBGROUPS                    412
#define IDC_STS_EPU                     413
#define IDC_NOTICE_USER                 414
#define IDC_EPU                         414
#define IDC_AUTH_PROFILE                415
#define DLG_CONFIG                      1001
#define IDC_PORT                        1002
#define IDC_PORT_EDIT                   1002
#define IDC_USER                        1006
#define IDC_PWD                         1007
#define IDC_AKI                         1008
#define IDC_PASSWORD                    1009
#define IDC_SAK                         1009
#define IDC_ST                          1010
#define IDC_PN                          1011
#define IDC_IDP_HOST                    1012
#define IDC_IDP_PORT                    1013
#define IDC_PR                          1014
#define IDC_LTRP                        1015
#define IDC_DGF                         1016
#define IDC_IDP_TENANT                  1017
#define IDC_DATASOURCE                  1018
#define IDC_AZURE_CI                    1018
#define IDC_AZURE_CS                    1019
#define IDC_TO                          1020
#define IDC_LOGIN_URL                   1021
#define IDC_LP                          1022
#define IDC_WIT                         1023
#define IDC_ROLE                        1024
#define IDC_DURATION                    1025
#define IDC_RSN                         1026
#define IDC_APP_ID                      1027
#define IDC_APP_NAME                    1028
#define IDC_LTRP2                       1029
#define IDC_SPID                        1029
#define IDC_PROVIDER_NAME               1030
#define IDC_SCOPE                       1031
#define IDC_TOKEN                       1032
#define IDC_TOKEN_TYPE                  1033
#define IDC_IDENTITY_NAMESPACE          1034
#define IDC_DESCTEXT                    1039
#define DRV_MSG_LABEL                   1040
#define DLG_PASSWORD                    1048
#define IDD_PROPPAGE_LARGE              1049
#define DLG_CSC                         1050
#define DLG_PROXY                       1051
#define IDC_OPTIONS                     1054
#define DRV_SHOWSYSTEMTABLES2           1054
#define DRV_OR_DSN                      1059
#define DRV_MSG_LABEL2                  1073
#define IDC_DRIVERNAME                  1076
#define DS_SERVERSIDEPREPARE2           1076
#define DS_EMU_ORA_REFCURSOR            1076
#define IDC_MANAGEDSN                   1077
#define IDC_TEST                        1085
#define IDC_CHECK3                      1117
#define IDC_DESC_PARAMS                 1117
#define IDC_USE_SSL                     1119
#define IDC_THREADS                     1120
#define IDC_COL_METADATA                1121
#define IDC_FETCH_REFCURSOR             1122
#define IDC_ROLLBACK_ERR                1123
#define IDC_LOGIN_TO                    1124
#define IDC_LOGIN_TO_EDIT               1124
#define IDC_LOGIN_TIME                  1125
#define IDC_READ_ONLY                   1125
#define IDC_QRY_TO                      1126
#define IDC_CURRENT_DB_ONLY             1126
#define IDC_PROXY_REDSHIFT_SERVER_EDIT  1126
#define IDC_QRY_TO_EDIT                 1127
#define IDC_PROXY_REDSHIFT_PORT_EDIT2   1127
#define IDC_PROXY_REDSHIFT_PORT_EDIT    1127
#define IDC_INI_SQL                     1128
#define IDC_PROXY_REDSHIFT_UID_EDIT     1128
#define IDC_INI_SQL_EDIT                1129
#define IDC_PROXY_REDSHIFT_PWD_EDIT     1129
#define IDC_RETRY                       1130
#define IDC_PROXY_HTTPS_SERVER_EDIT     1130
#define IDC_PROXY_HTTPS_PORT_EDIT       1131
#define IDC_RETRY_EDIT                  1132
#define IDC_PROXY_HTTPS_UID_EDIT        1132
#define IDC_DELAY                       1133
#define IDC_PROXY_HTTPS_PWD_EDIT        1133
#define IDC_RETRY_EDIT2                 1133
#define IDC_LOG_PATH_EDIT               1133
#define IDC_DELAY_EDIT                  1134
#define IDC_PASSWORD_EDIT               1135
#define IDC_DSNAME_STATIC               1136
#define IDC_DESC_STATIC                 1138
#define IDC_SERVER_STATIC               1140
#define IDC_PORT_STATIC                 1142
#define IDC_DBASE_STATIC                1144
#define IDC_CID_STATIC                  1145
#define IDC_USER_STATIC                 1146
#define IDC_PWD_STATIC                  1147
#define IDC_LOGIN_TO_STATIC             1148
#define IDC_REGION_STATIC               1148
#define IDC_DBUSER_STATIC               1149
#define IDC_PROXY_SERVER_STATIC         1149
#define IDC_RETRY_STATIC                1150
#define IDC_DBGROUPS_STATIC             1150
#define IDC_PROXY_PORT_STATIC           1150
#define IDC_AKI_STATIC                  1151
#define IDC_PROXY_UID_STATIC            1151
#define IDC_LOGLEVEL_STATIC             1151
#define IDC_DELAY_STATIC                1152
#define IDC_SAK_STATIC                  1152
#define IDC_PROXY_REDSHIFT_PWD_STATIC   1152
#define IDC_ST_STATIC                   1153
#define IDC_PROXY_SERVER_STATIC2        1153
#define IDC_LOGPATH_STATIC              1153
#define IDC_CONN_HELP                   1154
#define IDC_PROXY_PORT_STATIC2          1154
#define IDC_TAB1                        1155
#define IDC_PN_STATIC                   1155
#define IDC_PROXY_UID_STATIC2           1155
#define IDC_IDP_HOST_STATIC             1156
#define IDC_PROXY_REDSHIFT_PWD_STATIC2  1156
#define IDC_IDP_PORT_STATIC             1157
#define IDC_PR_STATIC                   1158
#define IDC_LTRP_STATIC                 1159
#define IDC_DGF_STATIC                  1160
#define IDC_QRY_TO_STATIC               1161
#define IDC_IDP_TENANT_STATIC           1161
#define IDC_AZURE_CI_STATIC             1162
#define IDC_INI_SQL_STATIC              1163
#define IDC_AZURE_CS_STATIC             1163
#define IDC_TO_STATIC                   1164
#define IDC_ADV_HELP                    1165
#define IDC_LOGIN_URL_STATIC            1165
#define IDC_LOAD_BALANCE                1166
#define IDC_LP_STATIC                   1166
#define IDC_ALT_SRV_STATIC              1167
#define IDC_WIT_STATIC                  1167
#define IDC_ALT_SRV_EDIT                1168
#define IDC_ROLE_STATIC                 1168
#define IDC_DURATION_STATIC             1169
#define IDC_RSN_STATIC                  1170
#define IDC_APP_ID_STATIC               1171
#define IDC_APP_NAME_STATIC             1172
#define IDC_FAIL_PRECONN                1173
#define IDC_SPID_STATIC                 1173
#define IDC_FAIL_HELP                   1174
#define IDC_PROVIDER_NAME_STATIC        1174
#define IDC_POOL_ENABLE                 1175
#define IDC_STS_EPU_STATIC2             1175
#define IDC_STS_EPU_STATIC              1175
#define IDC_POOL_RESET                  1176
#define IDC_EPU_STATIC                  1176
#define IDC_POOL_MAX_STATIC             1177
#define IDC_EPU_STATIC2                 1177
#define IDC_POOL_MAX_EDIT               1178
#define IDC_SCOPE_STATIC                1178
#define IDC_POOL_MIN_STATIC2            1179
#define IDC_POOL_MIN_EDIT               1180
#define IDC_POOL_IDLE_STATIC            1181
#define IDC_POOL_TO_EDIT                1182
#define IDC_POOL_HELP                   1183
#define IDC_FAIL_GRAN_LIST              1185
#define IDC_FAIL_MODE_GRP               1186
#define IDC_FM_CONN                     1187
#define IDC_FM_EXT_CONN                 1188
#define IDC_FM_SELECT                   1189
#define IDC_FG_NON_ATOMIC               1190
#define IDC_FG_ATOMIC                   1191
#define IDC_FG_REPOS                    1192
#define IDC_FG_NO_INT_CHECK             1193
#define IDC_CSC_ENABLE                  1194
#define IDC_EDIT_CSC_THRESHOLD          1195
#define IDC_EDIT_CSC_PATH               1196
#define IDC_EDIT_CSC_MAX_FILE_SIZE      1197
#define IDC_CSC_HELP                    1198
#define IDC_COMBO_EM                    1199
#define IDC_EDIT_SC_ROWS                1199
#define IDC_VSC                         1200
#define IDC_EDIT_HNIC                   1201
#define IDC_EDIT_HNIC2                  1202
#define IDC_EDIT_TS                     1202
#define IDC_SSL_HELP                    1203
#define IDC_CHECK1                      1204
#define IDC_COMBO_KSA                   1204
#define IDC_AUTO_CREATE                 1204
#define IDC_EDIT_TS2                    1205
#define IDC_EDIT_KSN                    1205
#define IDC_FLC                         1205
#define IDC_AUTH_TYPE_STATIC            1206
#define IDC_COMBO_AUTH_TYPE             1207
#define IDC_UIP                         1208
#define IDC_SSL_INSECURE                1209
#define IDC_VERSION_STATIC              1210
#define IDC_PROXY_REDSHIFT_CONNECTION   1211
#define IDC_PROXY_STS                   1213
#define IDC_PROXY_IDP                   1214
#define IDC_LOG_LEVEL_COMBO             1216
#define IDC_TOKEN_STATIC                1217
#define IDC_TOKEN_TYPE_STATIC           1218
#define IDC_IDENTITY_NAMESPACE_STATIC   1219
#define IDC_CHECK1                      1224
#define IDC_COMBO_KSA                   1224
#define IDC_SERVERLESS                  1224
#define IDC_CHECK1                      1225
#define IDC_COMBO_KSA                   1225
#define IDC_SERVERLESS_IDP_TOKEN        1225
#define IDC_WORKGROUP_STATIC            1226
#define IDC_WORKGROUP                   1227
#define IDC_GROUP_FEDERATION            1228
#define IDC_COMPRESSION_COMBO           1229
#define IDC_COMPRESSION_STATIC          1230

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1217
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
